Список контактов и детали контакта. Верстка и навигация
iaroslav18/AndroidLessons pull request #2
Opened 2020-04-29 16:38 UTC by iaroslav18

Добавлен фрагмент со списком контактов.
В списке реализована одна карточка контакта.
Добавлен фрагмент с деталями контакта.
Реализован переход между фрагментами.

hex цветов:
#4a1824 - colorPrimary
#735552 - colorAccent
![contactList](https://user-images.githubusercontent.com/58564569/80621516-15718780-8a50-11ea-9634-5e5068a47ff7.jpg)
![contactDetails](https://user-images.githubusercontent.com/58564569/80621524-173b4b00-8a50-11ea-8a16-bb5e62c5692e.jpg)

2020-04-29 17:07 UTC, goblinr requested changes

2020-04-29 17:07 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +    // TODO: Rename and change types and number of parameters
Это каким-то генератором было создано?

2020-04-29 17:07 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +            mParam2 = getArguments().getString(ARG_PARAM2);
Какой смысл в этих 2-х параметрах? 
В требованиях к ДЗ нужно было передать только 1 параметр - ID контакта

2020-04-29 17:07 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +    public static ContactDetailsFragment newInstance(String param1, String param2) {
Здесь явно копипаста.
Для ContactListFragment не нужны параметры

2020-04-29 17:07 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +        ContactDetailsFragment details = new ContactDetailsFragment();
Нужно передавать ID выбранного контакта в аргументы ContactDetailsFragment

2020-04-29 17:07 UTC, goblinr commented on app/src/main/res/layout/activity_main.xml
> +    <fragment
Тэг `<fragment>` нельзя использовать совместно с динамическим добавлением фрагментов

2020-04-29 17:07 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +            android:layout_height="35dp"
Нечетных размеров следует избегать.
Это касается всего проекта

2020-04-29 17:07 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <LinearLayout
Бессмысленное вложение других контейнеров в `ConstraintLayout`
Если используешь `ConstraintLayout` - то делай плоскую структуру - никаких вложений 3-го и более уровня

2020-04-29 19:34 UTC, iaroslav18 commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +    // TODO: Rename and change types and number of parameters
Это было создано AndroidStudio

2020-04-29 19:52 UTC, goblinr requested changes

2020-04-29 19:52 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +        super.onCreate(savedInstanceState);
Параметр paramId  нужно восстанавливать из аргументов

2020-04-29 19:52 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Бессмысленный LinearLayout всего с одним элементом внутри

2020-04-30 08:04 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Теперь бессмысленный ConstraintLayout. Если используешь ConstraintLayout, то структуру внутри него нужно делать плоской, т.е. не должно быть вложенности больше одной.

2020-04-30 11:14 UTC, goblinr approved these changes
Обнови скриншоты и можно мержить

2020-04-30 11:30 UTC, merged