Добавлен привязанный сервис для получения списка и деталей контактов
iaroslav18/AndroidLessons pull request #3
Opened 2020-05-11 19:38 UTC by iaroslav18

2020-05-12 04:16 UTC, goblinr requested changes

2020-05-12 04:16 UTC, goblinr commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"></service>
```xml
<service
            android:name=".ContactsService"
            android:enabled="true"
            android:exported="true" />
```

2020-05-12 04:16 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactsService.java
> +public class ContactsService extends Service {
Задание не сделано. По ТЗ нужно было выделить 2 публичных метода, оба метода должны быть асинхронными.
Данные методы должны вызывать фрагменты, а не получать данные в аргументах, как это у тебя сделано сейчас.

2020-05-18 05:05 UTC, goblinr requested changes

2020-05-18 05:05 UTC, goblinr commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"></service>
Не исправлено

2020-05-18 05:05 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +        setArguments(mainActivity.getContactDetails());
Зачем это?

2020-05-18 05:05 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +        setArguments(mainActivity.getContactList());
Зачем?

2020-05-18 05:05 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +        MainActivity mainActivity = (MainActivity) getActivity();
Зачем?

2020-05-18 05:05 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactsService.java
> +public class ContactsService extends Service {
Не исправлено

2020-05-18 05:05 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/MainActivity.java
>      }
Что это? Зачем?

2020-05-18 05:05 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/MainActivity.java
> +    }
И это тоже непонятно для чего?

2020-05-18 09:11 UTC, goblinr requested changes

2020-05-18 09:11 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +        setArguments(getContactDetails.doInBackground());
Нет. Это так не работает.
Здесь у тебя происходит блокирования основного потока в момент, когда ты вызываешь `getContactDetails.doInBackground()` 
Это касается и получения списка контактов, так же.

2020-05-18 09:11 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +        setArguments(getContactList.doInBackground());
блокирование основного потока программы

2020-05-18 15:00 UTC, goblinr requested changes

2020-05-18 15:00 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
>          fragment.setArguments(args);
Это так не работает. Нельзя думать, что ты передал одну и ту же ссылку в аргументы фрагмента и в асинхронную задачу и, что это решит проблему. Пересмотри лекцию про `BroadcastReceiver` там в конце я показываю, как делать асинхронное получение данных.

2020-05-18 15:00 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +        fragment.setArguments(args);
Здесь то же самое

2020-05-18 15:00 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactsService.java
> +public class ContactsService extends Service {
По-прежнему не исправлено. Избавься от `AsyncTask`'ов

2020-05-20 04:17 UTC, goblinr requested changes

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +        service = mainActivity.getService();
Привязываться жестко к `MainActivity` в фрагменте - плохо. Пересмотри 2-ю лекцию про взаимодействие на уровне Activity -> Fragment.

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactsService.java
> +        ExecutorService executor = Executors.newSingleThreadExecutor();
Каждый раз заново создавать `ExecutorService` - избыточно. Создай его один раз в конструкторе сервиса

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactsService.java
> +        executor.shutdown();
Этого делать не стоит

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactsService.java
> +        ExecutorService executor = Executors.newSingleThreadExecutor();
Сделай один `ExecutorService` на сервис

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactsService.java
> +        executor.shutdown();
убери

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +        setResources(view);
Это не верно. `setResources(view)` вызовется раньше чем произойдет вызов `getDetails()`. Соответственно, данные для обновления вьюшек еще не будут загружены в этот момент

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +        setResources(view);
Учитывай так же, что `getDetails()` вызывается на другом потоке, а вьюшки мы можем изменять только на главном потоке программы. Поэтому необходимо в момент когда данные загрузились, добавить отложенную работу на EventLooper главного потока по изменению данных в вьюшки через `Handler.post()` либо через `view.post()`

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +        setArguments(bundle);
`setArguments` предназначены исключительно для передачи **входных** данных в фрагмент, но никак не для хранения загруженных данных.

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +        service = mainActivity.getService();
см. комментарии выше

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +        setResources(view);
см. комментарии выше

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +        setArguments(bundle);
см. комментарии выше

2020-05-20 04:17 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/MainActivity.java
>                      .add(R.id.container, new ContactListFragment()).commit();
Здесь есть проблема. Транзакция фрагмента запускается до того, как произойдет `onServiceConnected`. Соответственно, фрагмент получит вместо рабочей ссылки на сервис - `null`

2020-05-21 06:12 UTC, goblinr requested changes

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
>          mainActivity.setTitle("Детали контакта");
Не исправлено, жесткая привязка к `MainActivity`

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +    private View view;
Ссылку на view необходимо обнулять в `onDestroyView()` для того что бы не было утечки памяти на время смены конфигурации и на то время пока фрагмент в бэкстэке находится.

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +    private View view;
Либо используй `WeakReference<View>`

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
> +                ImageView photo = view.findViewById(R.id.avatar);
Прежде чем обращаться к `view`, следует проверить ее на `null`

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
>          mainActivity.setTitle("Список контактов");
Не исправлена жесткая привязка к `MainActivity`

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +    private View view;
Обнулять ссылку в `onDestroyView` либо используй слабую ссылку

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactListFragment.java
> +                ImageView photo = view.findViewById(R.id.avatar);
Проверять на `null` перед обращением

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactsService.java
> +    private ExecutorService executor;
`final`

2020-05-21 06:12 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/MainActivity.java
>                      .add(R.id.container, new ContactListFragment()).commit();
Не исправлено. Операция привязывания сервиса - это асинхронная операция, поэтому запускать транзакцию нужно **после** того как ты получишь ссылку на сервис в `onServiceConnected`

2020-05-21 19:13 UTC, iaroslav18 commented on app/src/main/java/com/gmail/yarolave/lesson/MainActivity.java
>                      .add(R.id.container, new ContactListFragment()).commit();
Можете подсказать, как это исправить?

2020-05-22 04:58 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/MainActivity.java
>                      .add(R.id.container, new ContactListFragment()).commit();
Я же уже выше написал, что транзакцию нужно запускать после того как `onServiceConnected` отработает.

2020-05-28 09:25 UTC, goblinr requested changes

2020-05-28 09:25 UTC, goblinr commented on app/src/main/java/com/gmail/yarolave/lesson/ContactDetailsFragment.java
>          mainActivity.setTitle("Детали контакта");
Это нужно удалить. Уже 3 раза указывал на эти строки кода. Здесь жесткая привязка к `MainActivity` из-за чего фрагмент нельзя использовать вне `MainActivity`

2020-05-28 11:10 UTC, goblinr approved these changes

2020-05-28 11:40 UTC, merged